### ISSUE TITLE
is possible to set the attribute of resource set

### ISSUE THREAD

**Issue by chengyi** [01org/murphy#29]
Hi:
  I read the code, found that only resource has attribute, but resource set has no attribute.
I want to implement following scenario:
1. resource acquired by resource set A
2. resource set B wants to acquire the resource, but whether B can acquire the resource based on some
    status of the program which creates resource set A

@klihub could you give me some advices? thank you.

**Comment by klihub** [comment]
Hmm... I think this might be possible to do with server-side Lua scripting in the ruleset. Would you need to dynamically change the 'status' of the resource during the lifetime of the resource set of A ?

**Comment by chengyi** [comment]
@klihub yeah. But how to do this with server-side ruleset?

**Comment by klihub** [comment]
> @klihub yeah. But how to do this with server-side ruleset?

@chengyi I'll try to dig out an example for you...

Meanwhile, what about dynamicity ? Would you need to dynamically change the 'state/property' of the resource in resource set A, you mention in the original question, and without changing any other state of the whole resource set (IOW without changing the acquired state of set A) ?

**Comment by chengyi** [comment]
@klihub  let me show you the use case to make the scenario clearer :
just imagine that an in-vechicle Infotainment system, it has some apps like  music, phone,  voice recognition, radio:
1. you turn on the radio app.
2. you activate a voice recognition app, and it need to play a notification sound(resource set A acquire the speaker resource), and you tell it to open the music app to play music.
3. in case of your voice is unterstood by the voice recognition app, the speaker resource should acquired by music app (resource set B).
4. in case of your voice can not be unterstood by the voice recognition app, speaker resource should be released, and return to the radio app.

**Comment by klihub** [comment]
I'm, not sure if this requires such a complex setup as you think. I think this should work out of the box (provided you get voice recognition working) if you simply set up your radio and music players to be in the same application class ('player'), using the same exclusive audio playback resource ('audio_playback'), probably with the same 'music' role, and of course they both correctly obey the notifications of their corresponding resource sets.

IOW, I think this should simply work so that
  1) radio starts
    - acquires its resource set succesfully
     => plays radio
  2) voice recognition (or physical button, etc.)
  3a) OK, music player activated
    - music player acquires resource set
    => radio gets pre-empted and stops
  3b) not OK, music player not activated
    => radio keeps playing

**Comment by chengyi** [comment]
@klihub sorry, my statement may be not so clear, the key point is:
1. voice recognition app also acquire resource(need to play a tip tone), let's mark it as resource set C, and it has higher priority than radio and music player.

so the scenario is complex:
1. radio app start play
2. voice recognition start, and acquire the audio_playback resource, 
    (radio app stop play) then play a tip tone, and start listening and recognizing,
3a. if recognition is OK, the music app acquire the audio_playback resource from voice recognition app. (may be implemented using veto?)
3b. if recognition is FAIL,  voice recognition app released audio_playback resource, and radio start playing again.

**Comment by klihub** [comment]
If you make your voice recognition app able to start (the playback) on the music player, then I still think this should work out of the box. IOW, I would not try to implement the succesful-recognition logic with the murphy resource machinery at all. Instead I'd arrange it so that
  - the voice recognition app has higher priority and takes audio playback+recording (like you do)
  - voice recognition is able to start(/stop) the voice controlled applications (music, radio)
  - the voice controlled apps use the resources normally

**Comment by chengyi** [comment]
@klihub 
since the voice recognition app has higher priority, how the voice controlled apps (music, radio)  preempt the audio_playback resource from it? (the audio_playback resource is exclusive)

**Comment by klihub** [comment]
Once the voice recognition app has recognised the command, it should let the resource go until there is a a need for another command.

Or are you trying to run the voice recognition app continuously in the background (in which case it shouldn't/can't use resource sets) ? I'd be surprised if that can be made working with any reasonable accuracy...

**Comment by chengyi** [comment]
@klihub remember that voice recognition app take the audio_playback from radio as disscused above,
once it lets resource go when it has execute command that opening the music app, the resource is given back to radio(dont_wait property is false, because when the recognition fail, audio resource need to be given back to radio), then acquired by music app.  

This could lead to a little bit radio sound leaked from speaker before the music start playing. So I want to find a way that directly "move" the audio_playback resource from voice recognition app 
 to music app. maybe veto is a good solution?  but using veto, I must pass the  recognition result to murphy's lua layer, and this seems require more extra work.

**Comment by klihub** [comment]
We were solving this in the audio server (Pulseaudio) with a murphy-specific module (module-murphy-ivi). That module subscribed to policy decisions and enforced them immediately, already before the apps got around to react to pre-emption (losing the audio_playback resource). This was preventing the worst of these annoying overlapping transient states where an app that got audio playback rights managed to start playing before the one that got pre-empted had time to stop playing.

And to be honest, this was (a result of) one of the early architectural choice we made. There are really two ways to prevent unwanted transients in a distributed (audio) system like this:
 1. you make the whole pipeline, including policy decision making and the application-side processing, fully synchronous, with every state transition fully synchronized between all involved parties
 2. you make you audio server a policy-enforcement point which knows which clients are allowed to play and enforces this all the time

Attempting to make 1. working is usually a bad idea for anything which is not trivial. It's biggest problem is that all (audio) application logic inevitably and implicitly becomes part of your effective policy logic. IOW, you essentially distribute your effective policy logic among all the applications that might play audio. This implies that you start trusting all applications to work 100% right all the time, because otherwise it does not matter what your policy decides, if an applications misbehaves it breaks everything. This was the biggest reason to go with 2.

**Comment by chengyi** [comment]
@klihub got it. thanks a lot.

**Comment by klihub** [comment]
Related to this still... do you use Pulseaudio as your audio server ? If you do, do you have module-murphy-ivi there in use ?

**Comment by chengyi** [comment]
@klihub I do not use pulseaudio yet, because the product which I am working on make the mcu control the sound card. :confounded:

**Comment by klihub** [comment]
Okay, fair enough. We'll have a brainstorming session and try to come up with the best way for you to avoid the audio transients in your case, without pulseaudio...

**Comment by chengyi** [comment]
@klihub thanks a lot!:handshake:

**Comment by klihub** [comment]
@chengyi What is the interface/API/abstraction the various audio applications use to push PCM to the audio rendering pipeline ? Plain ALSA ?

**Comment by chengyi** [comment]
@klihub yes. the music app use gstreamer and alsa. radio send pcm through i2s bus.

**Comment by klihub** [comment]
> @klihub yes. the music app use gstreamer and alsa. radio send pcm through i2s bus.

Directly through i2s bus without an ALSA abstraction on top if it ?

**Comment by klihub** [comment]
Isn't i2s for the radio just a control channel for tuning and other control, and the actual audio is a loopback from the tuner to the some audio output on the MCU side ? So you actually don't deliver any PCM data, you just configure where it takes it from (tuning) and where it pushes it to (routing) without any PCM data ever coming to the linux side ?

**Comment by chengyi** [comment]
@klihub 
![arch](https://user-images.githubusercontent.com/6308364/75611186-318da100-5b53-11ea-9541-ce54c3762ca2.jpg)
as you can see, mcu  control dsp and tuner through i2c, soc and tuner send pcm to dsp, soc communicate with mcu throught uart.
when soc want to play some sound, it tell mcu to switch dsp's audio path. when user want to listen to radio, soc tell mcu to set dsp's audio path and activate radio. it's a horrible architecture:confounded:

**Comment by klihub** [comment]
Well, it looks a lot like one of the smartphone HW architectures that survived...

**Comment by chengyi** [comment]
@klihub :rofl::rofl::rofl:
